language: php
php:
    - '7.2'
    - '8.0'
before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction
script:
    phpunit
notifications:
    on_success: never
    on_failure: always
    